FROM node:20-bookworm-slim

RUN apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates curl ffmpeg python3 \
  && curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp \
  && chmod a+rx /usr/local/bin/yt-dlp \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY server/package*.json ./server/
COPY server/scripts ./server/scripts
RUN cd server && npm ci --omit=dev

COPY client/package*.json ./client/
RUN cd client && npm ci

COPY server ./server
COPY client ./client

ARG VITE_GOOGLE_CLIENT_ID=
ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
RUN cd client && npm run build

ENV NODE_ENV=production
ENV PORT=7860
ENV CLIENT_DIST=/app/client/dist
ENV CLIENT_ORIGIN=
ENV MAX_UPLOAD_MB=250
ENV INLINE_AUDIO_LIMIT_MB=8
ENV DATA_DIR=/data
ENV DATABASE_URL=
ENV POSTGRES_SSL=
ENV DATA_STORE_NAMESPACE=audio-studio
ENV DATA_STORE_TABLE=audio_studio_kv
ENV JWT_SECRET=audio-studio-change-this-secret
ENV SECRETS_MASTER_KEY=
ENV GOOGLE_CLIENT_ID=
ENV ADMIN_BOOTSTRAP_USERNAME=
ENV ADMIN_BOOTSTRAP_EMAIL=
ENV ADMIN_BOOTSTRAP_PASSWORD=
ENV ADMIN_BOOTSTRAP_RESET_PASSWORD=false
ENV EMAIL_DEV_CODES=true
ENV PROCESS_RATE_LIMIT=12
ENV INFO_RATE_LIMIT=45
ENV JSON_LIMIT=512kb
ENV YTDLP_FORCE_UPDATE=true
ENV YTDLP_PREFER_LOCAL=true
ENV YTDLP_STARTUP_UPDATE=true
ENV YTDLP_ENABLE_SECTIONS=true
ENV YTDLP_ALT_CLIENT_FALLBACKS=true
ENV YTDLP_FORCE_IPV4=true
ENV YTDLP_LEGACY_SERVER_CONNECT=false
ENV YTDLP_NO_CHECK_CERTIFICATES=false
ENV YTDLP_SOCKET_TIMEOUT=15
ENV YTDLP_RETRIES=2
ENV YTDLP_FRAGMENT_RETRIES=2
ENV YTDLP_EXTRACTOR_RETRIES=4
ENV YTDLP_RETRY_SLEEP=extractor:linear=1::4
ENV YTDLP_CONCURRENT_FRAGMENTS=1
ENV YOUTUBE_DOWNLOAD_ORDER=direct-section,direct-url,ytdl-core,yt-dlp
ENV YTDLP_GET_URL_TIMEOUT_MS=120000
ENV YTDLP_SECTION_TIMEOUT_MS=120000
ENV YTDLP_DOWNLOAD_TIMEOUT_MS=90000
ENV YOUTUBE_DIRECT_SECTION_TIMEOUT_MS=120000
ENV FREE_CONVERT_LIMIT=3
ENV FREE_DURATION_LIMIT_SECONDS=600
ENV APP_NAME="Audio Studio"
ENV APP_PUBLIC_URL=
ENV APP_COLOR=#06b6d4
ENV SMTP_HOST=
ENV SMTP_PORT=587
ENV SMTP_SECURE=false
ENV SMTP_USER=
ENV SMTP_PASS=
ENV EMAIL_FROM=
ENV MIDTRANS_SERVER_KEY=
ENV MIDTRANS_CLIENT_KEY=
ENV MIDTRANS_PRODUCTION=false

EXPOSE 7860

CMD ["node", "server/scripts/start-server.mjs"]
